[project]
name = "backend"
version = "0.0.1"
requires-python = ">=3.14,<3.15"
dependencies = [
    "uvicorn",
    "django-ninja",
    "python-dotenv",
    "django-simpleui",
    "psycopg[binary,pool]",
]
